name: jwalli
description: A new Flutter application.

publish_to: 'none' 
version: 1.0.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hexcolor: 2.0.5
  shared_preferences: ^2.0.5
  image_picker: ^0.7.5+3
  fluttertoast: ^7.1.8
  conditional_builder: ^1.0.2
  pin_code_fields:
  slide_countdown_clock:
  carousel_pro: ^1.0.0
  flutter_rating: ^0.0.2
  auto_size_text: ^2.1.0
  geolocator: ^7.2.0+1
  geocoding: ^2.0.0
  bubble: ^1.2.1
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.8
  flutter_bloc: ^7.0.1
  dio: ^4.0.0
  intl: ^0.17.0
  loading_indicator:
  socket_io_client: 1.0.0
  flutter_local_notifications:
  path_provider: ^2.0.2
  http: ^0.13.4

  image_cropper: ^1.4.0
  flutter_image_compress: ^1.1.0
  font_awesome_flutter: ^9.1.0
  webview_flutter:
  awesome_dialog: ^2.1.0
  get_it:
  rflutter_alert: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.0.0
  url_launcher:



  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/ios_icon.png"
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
